### ISSUE TITLE
Having more than two all day events stacks the rest on top of each other in the day view window

### ISSUE THREAD

**Issue by kyleLPG** [williamtroup/Calendar.js#90]
Hey creator,

I've hooked the calendar up to some data that can potentially have around 50 all day events happening on the same day. Unfortunately, having any more than 2 all day events stacks 2nd -> nth events on top of each other at 11am in the day view.

![image](https://user-images.githubusercontent.com/59813537/210481395-ff008aa8-5db0-4004-9fc0-9b3c59b6daa8.png)

![image](https://user-images.githubusercontent.com/59813537/210481456-d03c33c0-5281-459c-b3ab-13c1ef799f1c.png)

**Comment by williamtroup** [comment]
Hello.  Looks like you didn't set the events as all-day events.  All Day events are not tied to specific times, so they would be stacked at the top instead.  Check your events via the Event Editor dialog.

**Comment by williamtroup** [comment]
The property on the JSON for an event is called "isAllDay".  Set that to true if you are doing it via JSON data only.

**Comment by DanThemes** [comment]
If you add a third event at 11:00 (second screenshot above) you won't be able to see it. I think placing the events one below the other (non-absolute positioned, just like the default full month view where the cell gets bigger to accommodate all the events added on the same day) within the full-week view would be better. So, if "defaultEventDuration" is set to 60 and "views.fullWeek.minutesBetweenSections" is set to 60, then a double click within the 11:00-12:00 slot would create an event tied to that entire hour (non-editable time, since events/appointments usually start at the top of the hour anyway). Would you consider adding in a future release a boolean option which would make events behave this way?
